config/routes.rb
Rails.application.routes.draw do

  namespace :backend do resources :offices end
  namespace :backend do resources :file_records end
  namespace :backend do resources :persons end
  devise_for :users
  root 'welcome#index'
  resources :file_records do
    resources :steps
    post 'archivate'
    collection do
      get :search
    end
  end
  resources :offices
  resources :people
  

  

end

app/models/file_record.rb
class FileRecord < ActiveRecord::Base
  has_many :steps, dependent: :destroy
  
  after_create :create_first_step
  
  def archivate
    steps.build.archivate
  end
  
  def save_step
    office = Office.last!
    steps.create! office: office
  end
  
  def create_first_step
    steps.build.first_step
  end
    
  def self.search keyword, office = nil
    if office
      search_by_keyword(keyword) & search_by_office(office)
    else
      search_by_keyword(keyword)
    end
  end

  private
  
  def self.search_by_keyword keyword
    FileRecord.where("title like '%#{ keyword }%'")
  end
  
  def self.search_by_office office
    file_records = []
    FileRecord.all.each do |file_record|
      file_record.steps.each do |step|
        if step.office.name == office
          file_records << file_record
        end
      end
    end
    file_records
  end

end

app/models/office.rb
class Office < ActiveRecord::Base
  
  has_many :steps
  
  def self.start_office
    Office.find_or_create_by name: 'Mesa de Entrada'
  end
  
  def self.archivate
    Office.find_or_create_by name: 'Archivo'
  end
  
  validates :name, presence: true,
                    length: { minimum: 2 }
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :steps
  
  #validates :name, presence: true, length: { minimum: 3 }
  #validates :dni, presence: true, length: { minimum: 7 }
  
  def completed?
    name && email && dni
  end
  
end

app/models/record.rb
class Record < ActiveRecord::Base
  has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  
  attr_accessor :email

  belongs_to :office
  belongs_to :person
  belongs_to :file_record
  
  before_create :save_person_by_email
  
  def archivate
    self.office = Office.archivate
    save
  end

  def self.archivate
    create office: Office.archive_office
  end
  
  def first_step
    self.office = Office.start_office
    save
  end
  
  private
  
  def save_person_by_email
    self.person = Person.find_or_create_by email: email if email
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend/file_records_controller.rb
class Backend::FileRecordsController < Backend::ApplicationController

  before_action :authenticate_user!
  
end

app/controllers/backend/offices_controller.rb
class Backend::OfficesController < Backend::ApplicationController
end

app/controllers/backend/persons_controller.rb
class Backend::PersonsController < Backend::ApplicationController
end

app/controllers/file_records_controller.rb
class FileRecordsController < InheritedResources::Base

  def archivate
    @file_record = FileRecord.find(params[:file_record_id]).archivate
    redirect_to file_records_path
  end

  def index
    @file_records = FileRecord.search(params[:q])
  end

  private

    def file_record_params
      params.require(:file_record).permit(:title, :search_keyword)
    end

end

app/controllers/offices_controller.rb
class OfficesController < InheritedResources::Base

  private
    def office_params
      params.require(:office).permit(:name)
    end

end

app/controllers/people_controller.rb
class PeopleController < InheritedResources::Base

  private

  def person_params
    params.require(:person).permit(:name, :dni)
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def create
    @file_record = FileRecord.find(params[:file_record_id])
    person = Person.find_or_create_by({email: params[:step][:email]})
    if person.completed?
      @file_record.steps.create(step_params)
      redirect_to file_record_path(params[:file_record_id])
    else
      redirect_to edit_person_path(person.id)
    end
  end
  
  private

  def step_params
    params.require(:step).permit(:file_record_id, :office_id, :person_id)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_record_helper.rb
module FileRecordHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/backend/application/_footer.html.erb
<footer>
  <p>&copy; Company 2013</p>
</footer>

app/views/backend/application/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-backend-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-backend-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/file_records/_form.html.erb
<%= form_for @file_record do |f| %>
 
  <% if @file_record.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@file_record.errors.count, "error") %> prohibited
        this office from being saved:
      </h2>
      <ul>
        <% @file_record.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/file_records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Back', file_records_path %>

app/views/file_records/index.html.erb
<h1>Listing file_records</h1>

<form name="input" action="file_records" method="get">
  Search by name: <input type="text" name="q">
  Search by office: <input type="text" name="o">
  <input type="submit" value="Submit">
</form>

<table>
  <tr>
    <th>file_record</th>
  </tr>
 
  <% @file_records.each do |file_record| %>
    <tr>
      <td><%= file_record.title %></td>
      <td><%= link_to 'Show', file_record_path(file_record) %></td>
      <td><%= link_to 'Edit', edit_file_record_path(file_record) %></td>
      <td><%= button_to 'Destroy', file_record_path(file_record),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %>
<%= link_to 'New', new_file_record_path %>

app/views/file_records/new.html.erb
<h1>New Records</h1>

<%= render 'form' %>
 
<%= link_to 'Back', file_records_path %>

app/views/file_records/search.html.erb
<h1>Search</h1>
 
<table>
  <tr>
    <th>file_record</th>
  </tr>
 
  <% @file_records.each do |file_record| %>
    <tr>
      <td><%= file_record.title %></td>
      <td><%= link_to 'Show', file_record_path(file_record) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %>
<%= link_to 'New', new_file_record_path %>

app/views/file_records/show.html.erb
<h1>Show File Record</h1>

<p>
  <strong>Title: </strong>
  <%= @file_record.title %><br>

  <strong>In office: </strong>
  <%= @file_record.steps.last.office.name %>
</p>

<h1>Step</h1>
<pre><h1> Office: Person:</h1></pre>

<%= form_for([@file_record, @file_record.steps.build]) do |f| %>
  <p>
    <%= collection_select(:step, :office_id, Office.all, :id, :name) %>
    <%= collection_select(:step, :person_id, Person.all, :id, :name) %>
  <p>
  <%= f.submit %>
  </p>
  <% end %>
  
  <%= button_to 'Archivate', file_record_archivate_path(@file_record) %>

  <p>
    <strong>History of steps:</strong><br>

    <% @file_record.steps.each do |step| %>
      <% if step.office_id != nil %>
        <%= step.office.name %><br>
      <% end %>
    <% end %>
  </p>

<br>
<%= link_to 'Back', file_records_path %>
<%= link_to 'Edit', edit_file_record_path(@file_record) %>

app/views/layouts/backend/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dummy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "backend", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div id="wrap">
      <%= render 'navigation' %>
      <%= render 'action_bar'%>

      <div class="container">
        <%= render 'messages' %>
        <%= yield %>
      </div>
    </div> <!-- /container -->
    <%= render 'footer'%>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "backend" %>
    
    <div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>.
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
</div>
  </body>
</html>

app/views/offices/_form.html.erb
<%= form_for @office do |f| %>
 
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@office.errors.count, "error") %> prohibited
        this office from being saved:
      </h2>
      <ul>
        <% @office.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>Listing offices</h1>
 
<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @offices.each do |office| %>
    <tr>
      <td><%= office.name %></td>
      <td><%= link_to 'Show', office_path(office) %></td>
      <td><%= link_to 'Edit', edit_office_path(office) %></td>
      <td><%= button_to 'Destroy', office_path(office),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %>
<%= link_to 'New', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>
 
<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<h1>Office show</h1>

<p><%= @office.name%></p>

<%= link_to 'Back', offices_path %>
<%= link_to 'Edit', edit_office_path(@office) %>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this office from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>
 
<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @people.each do |person| %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.dni %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= button_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %>
<%= link_to 'New', new_person_path %>

app/views/people/new.html.erb
<h1>New People</h1>

<%= render 'form' %>
 
<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<h1>Person show</h1>

<p><%= @person.name%></p>
<p><%= @person.dni%></p>

<%= link_to 'Back', people_path %>
<%= link_to 'Edit', edit_person_path(@person) %>

app/views/records/_form.html.erb
<%= form_for @record do |f| %>
 
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@record.errors.count, "error") %> prohibited
        this office from being saved:
      </h2>
      <ul>
        <% @record.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>
 
<table>
  <tr>
    <th>Record</th>
  </tr>
 
  <% @records.each do |record| %>
    <tr>
      <td><%= record.id %></td>
      <td><%= link_to 'Show', record_path(record) %></td>
      <td><%= link_to 'Edit', edit_record_path(record) %></td>
      <td><%= button_to 'Destroy', record_path(record),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/records/new.html.erb
<h1>New Records</h1>

<%= render 'form' %>
 
<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<h1>Record show</h1>

<p><%= @record.title %></p>
<%= render @record.steps %>

<%= link_to 'Back', records_path %>
<%= link_to 'Edit', edit_record_path(@record) %>

app/views/steps/_form.html.erb
<%= form_for @step do |f| %>
 
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@step.errors.count, "error") %> prohibited
        this office from being saved:
      </h2>
      <ul>
        <% @step.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.select(:office_id) do %>
    <% Office.all.each do |office| %>
      <%= content_tag(:option, office.name, value: office.id) %>
    <% end %>
  <% end %>

  <p>
    <%= f.hidden_field :file_record_id, value: @file_record.id %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/steps/_steps.html.erb
<h1>Listing steps</h1>
 
<table>
  <tr>
    <th>step</th>
  </tr>
 
  <% @file_record.steps.each do |step| %>
    <tr>
      <td><%= step.office.name %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Inicio para archivo tutoria</p>

<%= link_to 'Offices', controller: 'offices' %>

<%= link_to 'People', controller: 'people' %>

<%= link_to 'FileRecords', controller: 'file_records' %>